### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by bcheggeseth** [katelynmcclure/final_course_project#1]
**Requested File Structure**
- [x] code
- [x] data
- [x] planning with Milestone1.qmd  

**.gitignore**
- [x] Created a .gitignore file
- [x] Contains all of the request files in it

**Milestone2.qmd**
- [x] Progress on the stated plan
- [x] Future plan for Milestone 3
- [x] Included sessionInfo() at the end of qmd files

General Feedback:

- This is shaping up to be a really interesting project; collaborating with a community partner is a good challenge. Make sure to balance your interests with the interests and desires of the team. 
- Using ML is fine to help support the data storytelling. Think carefully about assumptions being made in wrangling and modeling process. Which variables and in what format are going to be included?

Collaboration:

- I will check git commit history to ensure all members are contributing to the project. 
- It looks like there has been a good balance between you two.
