### ISSUE TITLE
Milestone 5 Plan

### ISSUE THREAD

**Issue by katelynmcclure** [katelynmcclure/final_course_project#2]
**A brief description of your project research questions**
In collaboration with the Macalester Women's Volleyball Team, we are using Macalester Volleyball data from the [Macalester Athletics](https://athletics.macalester.edu/sports/2008/1/29/VB_0129081140.aspx) website. Here are our two main questions:

- Can the outcome of a game be predicted based on statistics from previous games/seasons? How accurate are these models? Can we make these models in an interactive way that can be used for seasons to come? 

- How have senior players changed/improved over their time on the Macalester volleyball team? Are there any interesting trends? In which game statistics have the seniors improved the most? 

**A brief description of the planned digital artifact**
We plan to make a Shiny app to allow for interactivity with the predictive win/loss model. We want to allow for the user to select which seasons and which game statistics are considered in the model, with some guidance on what the "best" model is, what the model that the coaches asked us to make is, etc. Our work surrounding the seniors over time question will not be interactive and rather live in a separate tab within the Shiny app. 

**Tasks:**

- [x] rewrite model creation code into functions - Katelyn - 12/2
- [x] how to visualize/explain stuff about model coeffs - Katelyn - 12/2
- [ ] decide what stats to track over time (and how to visualize) - Kynan - 12/4
- [x] create a shiny app - Kynan & Katelyn - 12/4
- [x] different tabs (model, static) - 12/4
- [ ] craft cohesive data story - Kynan & Katelyn - 12/10
- [ ] clean up visualization - Both - 12/14
- [ ] Codebook - either - 12/8
- [ ] comments in code - both - 12/14
