### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by lsokolew** [katelynmcclure/final_course_project#3]
**Requested File Structure**
- [x] results folder 
- [x] with Milestone3-Blog.qmd 
- [x] with rendered html
- [x] Included sessionInfo() at the end of qmd files

**Progress from Milestone 2**
- [x] Progress on the stated plan

**Milestone3-Blog**
- [ ] < 1000 words
- ~1,300
- [x] Motivate the importance of the topic
- I like the technique of identifying a gap in how data is currently being used and arguing that your analysis will fill that gap
- [x] Lead the reader through the rationale for the narrowing/focusing of the scope via the main 2-3 broad questions
- love that you are doing an analysis with direct, real-world applications, and addressing the questions of those who will benefit most from it!
- [x] Tie results (plots and modeling output) to the broad questions and explain how all results fit together
- Could have been nice to do a little more of this, although I can tell you're being careful about drawing conclusions when you have limited data
- [x] End with main takeaways, limitations with regard to the data context and ethical considerations, and future directions
